### PR TITLE
Update GitHub Actions CI script

### PR DESCRIPTION
**Pull request by git-developer**
This PR updates GitHub Action components to up-to-date versions and enables support for Ubuntu 24.04 (Noble Numbat). It is triggered by creation of a GitHub release or on manual action.

### CODE REVIEW

**Comment by C0rn3j** [comment]
Could you also remove support for lunar and mantic? 

If they're not EOL already, they will be soon, and there's a newer LTS available anyway.

**Comment by git-developer** [comment]
That's true, but I nevertheless kept them on purpose. The reason is compatibility. Let me explain.

Although one main goal of an AppImage is isolation from the host, there are still some requirements. For example, a lot of apps require a compatible glibc on the host (although it could be included in the AppImage instead). sc-controller additionally requires some UI components from Gnome. The AppImage is built against a certain version of Gnome that must be compatible to Gnome on the host.

Unfortunately, Gnome releases are not always backwards-compatible. Ubuntu Lunar & Mantic contain Gnome 44 & 45. If we remove them, we remove support for host distros using these versions (no matter if the host is Ubuntu or something else). I remember that it was hard to get the AppImage work within the gaming distro batocera due to these reasons.

I checked that an Ubuntu base image is still available on Docker Hub when its release is going EOL. So our AppImage build should be safe to run.

I'd like to keep these AppImages within the CI build for these reasons.

**Comment by C0rn3j** [comment]
https://wiki.ubuntu.com/Releases  
https://release.gnome.org/calendar/

Lunar is dead-dead, both the GNOME version you wish to support, and the distribution itself, so please do throw that one out.

Mantic is dead as of the upcoming July, I suppose keeping it there til then doesn't hurt anything.  
I don't wish to enable insecure EOL software, people can build it themselves if they need it there for whatever reason, or just keep using old SC versions until they find the time to fix their installation.

**Comment by git-developer** [comment]
OK, I see your point. Since older scc releases are still available, everyone should be able to find a matching AppImage.

**Comment by git-developer** [comment]
Looks like the ci build was not triggered on creation of release 0.4.8.16. Did you enable GitHub actions for this repo?

**Comment by C0rn3j** [comment]
I haven't, I have just been looking into that, meanwhile if you have some spare time, you could look into fixing the rest of the deprecations in scc-linux, or I'll get to look at it later.

```yaml
Node.js 16 actions are deprecated.  
Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4.  
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by C0rn3j** [comment]
Hmm, at least from a manual build, release gets completely skipped in this state, I am not too familiar with Actions to be able to easily debug why

**Comment by git-developer** [comment]
This is on purpose. If a build is triggered on release, the release number is known. If you manually trigger a build, the version is unknown. So you could either create a new release or delete 0.4.8.16 and re-create it afterwards.

**Comment by C0rn3j** [comment]
I see, I'll tag a .17 after I finish up my next commit to considerably slash the repo+installed filesize.

**Comment by git-developer** [comment]
That sounds good. BTW: a GitHub release is not the same as a git tag. Tagging will neither trigger a ci build nor a release. You have to explicitely create a release, where you can re-use an existing tag or give a new one.

**Comment by git-developer** [comment]
> The reason is compatibility.
> [...]
> I remember that it was hard to get the AppImage work within the gaming distro batocera due to these reasons.

Just for the record: the Lunar AppImage is strictly required for the scc gui in current batocera (39). Neither Jammy, Mantic nor Noble work:

* Latest stable batocera (39) comes with glibc 2.37 and glib 2.76
* Mantic and Noble AppImages require glibc 2.38 => incompatible
* Jammy AppImage requires glibc 2.35 and contains glib 2.72
* With the Jammy AppImage, the scc gui crashes with `Failed to load shared library 'libgdk-3.so.0' referenced by the typelib: /usr/lib64/libgdk-3.so.0: undefined symbol: g_string_free_and_steal`. This symbol [came with](https://docs.gtk.org/glib/method.String.free_and_steal.html) glib 2.76.
* So the host (batocera 39 / glib 2.76) requires an AppImage with glib 2.76, but Jammy contains 2.72 => crash
* The Lunar AppImage requires glibc 2.37 and uses glib 2.76, a perfect match for batocera 39.

Next stable batocera version (40) will contain glibc 2.38 and is scheduled for 2024-07. This should solve the problem.

**Pull request merged**
